### ISSUE TITLE
TS Error: Cannot read properties of undefined (reading 'open')

### ISSUE THREAD

**Issue by MrXinMumbai** [NathanWalker/ns-opennative-razorpay#1]
I get the error TypeError: Cannot read properties of undefined (reading 'open') when I tap on "Open RazorPay" button

**Comment by NathanWalker** [comment]
Hi @MrXinMumbai when possible, try running this: `echo 'y' | npx nativescript-envinfo`
and paste the output in full here.

**Comment by MrXinMumbai** [comment]
outout of echo 'y' | npx nativescript-envinfo

```yaml
OS: Windows 11 10.0.22631
CPU: (4) x64 Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz
Shell: Not Found
node: 18.20.4
npm: 10.7.0
nativescript: Not Found

# android
java: 17.0.13
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: Not Found
cocoapods: Not Found
python: 3.12.6
python3: Not Found
ruby: Not Found
platforms: Not Found
```

### Dependencies

```json
"dependencies": {
  "@angular/animations": "~19.0.0",
  "@angular/common": "~19.0.0",
  "@angular/compiler": "~19.0.0",
  "@angular/core": "~19.0.0",
  "@angular/forms": "~19.0.0",
  "@angular/platform-browser": "~19.0.0",
  "@angular/platform-browser-dynamic": "~19.0.0",
  "@angular/router": "~19.0.0",
  "@nativescript/angular": "^19.0.0",
  "@nativescript/core": "~8.8.0",
  "@open-native/core": "^2.0.4",
  "react-native-razorpay": "2.3.0",
  "rxjs": "~7.8.0",
  "zone.js": "~0.15.0"
},
"devDependencies": {
  "@angular-devkit/build-angular": "~19.0.0",
  "@angular/compiler-cli": "~19.0.0",
  "@nativescript/android": "8.9.0-dev.0",
  "@nativescript/ios": "8.8.2",
  "@nativescript/tailwind": "^2.1.0",
  "@nativescript/types": "~8.8.0",
  "@nativescript/webpack": "~5.0.0",
  "@ngtools/webpack": "~19.0.0",
  "@types/react-native-razorpay": "^2.2.6",
  "glob": "^10.0.0",
  "metro-react-native-babel-preset": "^0.77.0",
  "patch-package": "^8.0.0",
  "tailwindcss": "~3.4.0",
  "typescript": "~5.6.0"
}
```


Thanks...
